// Code generated by sqlc. DO NOT EDIT.
// source: report.sql

package db

import (
	"context"
)

const getHoursByEmpID = `-- name: GetHoursByEmpID :one
select sum(hours)  from timecard_record 
	where card_id = 
		( select id from timecard where emp_id = 1)
`

func (q *Queries) GetHoursByEmpID(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getHoursByEmpID)
	var sum interface{}
	err := row.Scan(&sum)
	return sum, err
}
