// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"fmt"
)

type EmployeesPaymentMethod string

const (
	EmployeesPaymentMethodPickUp  EmployeesPaymentMethod = "pick_up"
	EmployeesPaymentMethodMail    EmployeesPaymentMethod = "mail"
	EmployeesPaymentMethodDeposit EmployeesPaymentMethod = "deposit"
)

func (e *EmployeesPaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmployeesPaymentMethod(s)
	case string:
		*e = EmployeesPaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for EmployeesPaymentMethod: %T", src)
	}
	return nil
}

type EmployeesType string

const (
	EmployeesTypeHour         EmployeesType = "hour"
	EmployeesTypeSalaried     EmployeesType = "salaried"
	EmployeesTypeCommissioned EmployeesType = "commissioned"
)

func (e *EmployeesType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmployeesType(s)
	case string:
		*e = EmployeesType(s)
	default:
		return fmt.Errorf("unsupported scan type for EmployeesType: %T", src)
	}
	return nil
}

type Employee struct {
	ID                    int64                  `json:"id"`
	Name                  sql.NullString         `json:"name"`
	Password              sql.NullString         `json:"password"`
	Type                  EmployeesType          `json:"type"`
	Mail                  sql.NullString         `json:"mail"`
	SocialSecurityNumber  sql.NullString         `json:"social_security_number"`
	StandardTaxDeductions sql.NullString         `json:"standard_tax_deductions"`
	OtherDuductions       sql.NullString         `json:"other_duductions"`
	PhoneNumber           sql.NullString         `json:"phone_number"`
	Rate                  sql.NullString         `json:"rate"`
	HourLimit             sql.NullInt32          `json:"hour_limit"`
	PaymentMethod         EmployeesPaymentMethod `json:"payment_method"`
}

type EmployeeAccount struct {
	ID            int64          `json:"id"`
	BankName      sql.NullString `json:"bank_name"`
	AccountNumber sql.NullString `json:"account_number"`
}

type OrderInfo struct {
	OrderID   sql.NullInt64 `json:"order_id"`
	ProductID sql.NullInt64 `json:"product_id"`
	Amount    sql.NullInt32 `json:"amount"`
}

type Paycheck struct {
	ID        int64          `json:"id"`
	EmpID     sql.NullInt64  `json:"emp_id"`
	Amount    sql.NullString `json:"amount"`
	StartDate sql.NullTime   `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
}

type PurchaseOrder struct {
	ID              int64          `json:"id"`
	EmpID           sql.NullInt64  `json:"emp_id"`
	CustomerContact sql.NullString `json:"customer_contact"`
	CustomerAddress sql.NullString `json:"customer_address"`
	OrderInfoID     sql.NullInt64  `json:"order_info_id"`
	Date            sql.NullTime   `json:"date"`
	Status          sql.NullInt32  `json:"status"`
}

type Timecard struct {
	ID          int64         `json:"id"`
	EmployeesID sql.NullInt64 `json:"employees_id"`
	StartDate   sql.NullTime  `json:"start_date"`
	EndDate     sql.NullTime  `json:"end_date"`
	Status      sql.NullInt32 `json:"status"`
}

type TimecardRecord struct {
	ID           int64         `json:"id"`
	ChargeNumber sql.NullInt64 `json:"charge_number"`
	CardID       sql.NullInt64 `json:"card_id"`
	Hours        sql.NullInt32 `json:"hours"`
	Date         sql.NullTime  `json:"date"`
}
